CREATE DATABASE `jugos_ventas` 
/*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ 
/*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `facturas` (
  `DNI` varchar(11) NOT NULL,
  `MATRICULA` varchar(5) NOT NULL,
  `FECHA_VENTA` date DEFAULT NULL,
  `NUMERO` int NOT NULL,
  `IMPUESTO` float NOT NULL,
  PRIMARY KEY (`NUMERO`),
  KEY `MATRICULA` (`MATRICULA`),
  KEY `CPF` (`DNI`),
  CONSTRAINT `facturas_ibfk_1` FOREIGN KEY (`MATRICULA`) REFERENCES `tabla_de_vendedores` (`MATRICULA`),
  CONSTRAINT `facturas_ibfk_2` FOREIGN KEY (`DNI`) REFERENCES `tabla_de_clientes` (`DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `items_facturas` (
  `NUMERO` int NOT NULL,
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` float NOT NULL,
  PRIMARY KEY (`NUMERO`,`CODIGO_DEL_PRODUCTO`),
  KEY `CODIGO_DEL_PRODUCTO` (`CODIGO_DEL_PRODUCTO`),
  CONSTRAINT `items_facturas_ibfk_1` FOREIGN KEY (`CODIGO_DEL_PRODUCTO`) REFERENCES `tabla_de_productos` (`CODIGO_DEL_PRODUCTO`),
  CONSTRAINT `items_facturas_ibfk_2` FOREIGN KEY (`NUMERO`) REFERENCES `facturas` (`NUMERO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tabla_de_clientes` (
  `DNI` varchar(11) NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `DIRECCION_1` varchar(150) DEFAULT NULL,
  `DIRECCION_2` varchar(150) DEFAULT NULL,
  `BARRIO` varchar(50) DEFAULT NULL,
  `CIUDAD` varchar(50) DEFAULT NULL,
  `ESTADO` varchar(2) DEFAULT NULL,
  `CP` varchar(8) DEFAULT NULL,
  `FECHA_DE_NACIMIENTO` date DEFAULT NULL,
  `EDAD` smallint DEFAULT NULL,
  `SEXO` varchar(1) DEFAULT NULL,
  `LIMITE_DE_CREDITO` float DEFAULT NULL,
  `VOLUMEN_DE_COMPRA` float DEFAULT NULL,
  `PRIMERA_COMPRA` bit(1) DEFAULT NULL,
  PRIMARY KEY (`DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tabla_de_productos` (
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `NOMBRE_DEL_PRODUCTO` varchar(50) DEFAULT NULL,
  `TAMANO` varchar(10) DEFAULT NULL,
  `SABOR` varchar(20) DEFAULT NULL,
  `ENVASE` varchar(20) DEFAULT NULL,
  `PRECIO_DE_LISTA` float NOT NULL,
  PRIMARY KEY (`CODIGO_DEL_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tabla_de_vendedores` (
  `MATRICULA` varchar(5) NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `PORCENTAJE_COMISION` float DEFAULT NULL,
  `FECHA_ADMISION` date DEFAULT NULL,
  `VACACIONES` bit(1) DEFAULT NULL,
  `BARRIO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;